name: journeymate
description: A jogging app for route tracking and photo capture.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
<<<<<<< HEAD
  google_fonts: ^6.1.0
=======
>>>>>>> 53f304c196b69b67df568d758e51ad9b92d61f99

  # ✅ Updated Firebase packages
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6

  #Map
<<<<<<< HEAD
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  google_maps_flutter: ^2.12.2
  universal_io: ^2.2.2
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  location: ^8.0.1
  permission_handler: ^12.0.0+1

  # Image Picker
  image_picker: ^1.0.4
  camera: ^0.11.1
  path: ^1.9.0

=======
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  google_maps_flutter: ^2.12.2
  universal_io: ^2.2.2
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  location: ^5.0.3
  permission_handler: ^11.0.0

  # Image Picker
  image_picker: ^1.0.4
  camera: ^0.10.5
  path: ^1.9.0

  # Path Provider
  dio: ^5.4.0
  path_provider: ^2.1.2




>>>>>>> 53f304c196b69b67df568d758e51ad9b92d61f99

  # Record in the background
  provider: ^6.1.1


  # Animated
<<<<<<< HEAD
  animate_do: ^4.2.0
=======
  animate_do: ^3.0.2
>>>>>>> 53f304c196b69b67df568d758e51ad9b92d61f99

  # ✅ Video player
  video_player: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/JourneyMate_Logo.png
    - assets/Login_Background_Video.mp4
<<<<<<< HEAD
    - assets/default_profile.png
=======
>>>>>>> 53f304c196b69b67df568d758e51ad9b92d61f99

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/JourneyMate_Logo.png"
<<<<<<< HEAD

dependency_overrides:
  location_platform_interface: 5.0.0

=======
>>>>>>> 53f304c196b69b67df568d758e51ad9b92d61f99
